name: gobabel_client
description: The GO-Babel client package.
repository: https://github.com/Go-Babel/gobabel_client
issue_tracker: https://github.com/Go-Babel/gobabel_client/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod_client: 2.5.1
  serverpod_auth_client: 2.5.1